name: primer-workflow
on: [push]
jobs:
    hola-mundo:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set-up-Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - run: python main.py